### ISSUE TITLE
Fix repo language

### ISSUE THREAD

**Issue by ahmedig** [Insight-Services-APAC/azure-landing-zones#34]
The repository's language is misleading. It says Bicep making everyone think that we have a Bicep azure foundation version, but its just ARM templates.
This is an issue with GitHub Linguist, but luckily we can override it.

Please follow this guide.
https://github.com/github/linguist/blob/master/docs/overrides.md

**Comment by tulpy** [comment]
Thanks for this Ahmad, I had wondered why it was coming up as that, updated now to reflect ARM

**Comment by ahmedig** [comment]
Perfect! Thanks @tulpy! 
![image](https://user-images.githubusercontent.com/102851/128952241-4b9e5ee5-8d9b-4c64-a266-1fabff0d8f44.png)
