### ISSUE TITLE
Subnet, NSG in Arrays for Spoke 

### ISSUE THREAD

**Issue by aravindsundaram** [Insight-Services-APAC/azure-landing-zones#47]
**Is your feature request related to a problem? Please describe.**
Current bicep code to deploy spoke subnets fetches fixed subnets app, data and web from params. Any changes in subnet strucutre and number has to be tackled with code changes. 

**Describe the solution you'd like**
By introducing an array to process subnets and vnets gives the capablities to create Vnets and subnets in it based on arrays mentioned in params file.  NSGs are created for every subnet mentioned too. 
![image](https://user-images.githubusercontent.com/86707819/131306199-4dba8f16-27e4-456b-a376-0e21f1d9ad1f.png)
![image](https://user-images.githubusercontent.com/86707819/131306256-f7d9cf41-f890-41c8-a55a-dbdf23b326b3.png)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by tulpy** [comment]
This has been added to the new FB, please test and let me know any issues

https://github.com/Insight-Services-APAC/azure-landing-zones/tree/fb-sept2021/reference/spoke
